Add apply - a first attempt at adding the apply functionality
globaldothealth/adtl pull request #27
Opened 2023-02-21 15:47 UTC by pipliggins

2023-02-21 17:13 UTC, abhidg requested changes
Thanks, approach looks good; some changes required, could you also add tests for adtl/transformations.py?

2023-02-21 17:13 UTC, abhidg commented on adtl/__init__.py
> +            transformation = rule["apply"]["mappingType"]
I think `function` instead of `mappingType` would be better!

2023-02-21 17:13 UTC, abhidg commented on adtl/__init__.py
> +                        f"Error using a user-defined transformation: Function {transformation} has not been defined."
These are not user-defined transformations as adtl is supplying them.

2023-02-21 17:13 UTC, abhidg commented on adtl/transformations.py
> +    True if value != None and value != "" else False
needs a return, simpler to use `return value not in [None, ""]`, boolean expressions do not need True / False annotations.

2023-02-21 17:13 UTC, abhidg commented on adtl/transformations.py
> +    if birthdate == (None or "") or currentdate == (None or ""):
`birthdate in`, `currentdate in`, the right hand side of equality will resolve to "" so None is not being compared.

2023-02-21 17:13 UTC, abhidg commented on adtl/__init__.py
> +                    row[rule["apply"]["apply_params"][i]]
shorten to params?

2023-02-22 10:40 UTC, pipliggins commented
Okay, all done!

2023-02-22 13:46 UTC, abhidg approved these changes
Looks good, thanks!

2023-02-22 13:48 UTC, merged